# Generated by Django 4.1 on 2022-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0005_alter_file_existingpath"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
