# Generated by Django 4.1 on 2022-09-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
